### ISSUE TITLE
Not compatible with latest version of flutter_svg 

### ISSUE THREAD

**Issue by YassineChe** [mmolaei7878/marker_icon#1]
Hello,

Thank you for this package.

Can you please update the package 
Its not compatible with latest version of `flutter_svg`

I downgrade the version of `flutter_svg` it caused some issue with another's package 

i will appreciate if you could do it as soon as possible

**Comment by mmolaei7878** [comment]
Hi,
package updated 
please change package name and version
if there is an issue be in touch with me

**Comment by YassineChe** [comment]
Hello again!

The update isn't available on pub.dev!
Can you please push it over.

Thank you.
