### ISSUE TITLE
Another update

### ISSUE THREAD

**Issue by YassineChe** [mmolaei7878/marker_icon#2]
Hello,

Can you update the package to be compatible with the latest version of `flutter_svg: ^1.0.3`

Thank you so much!

**Comment by YassineChe** [comment]
@mmolaei7878, Can you please update it!?

**Comment by mmolaei7878** [comment]
Please fork it 🙏

**Comment by YassineChe** [comment]
> Please fork it 🙏

Done 👌🏻
Thanks
