### ISSUE TITLE
Flutter 3.0.2 Render Error _CastError (type 'Null' is not a subtype of type 'RenderRepaintBoundary' in type cast)

### ISSUE THREAD

**Issue by user-23xyz** [mmolaei7878/marker_icon#3]
This piece of cody is trowing me and error, any suggestions ?
RenderRepaintBoundary boundary = globalKey.currentContext?.findRenderObject() as RenderRepaintBoundary;

**Comment by mmolaei7878** [comment]
please fork and update dependencies 
sorry for late answer.

**Comment by mt-ks** [comment]
Same issue
